# Generated by Django 4.2.5 on 2023-10-28 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=None),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
