# Generated by Django 4.2.5 on 2023-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_category_key_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='None'),
        ),
    ]
