# Generated by Django 4.2.5 on 2023-11-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0008_alter_item_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('auth_date', models.PositiveIntegerField(verbose_name='telegram id profile')),
                ('first_name', models.CharField(verbose_name='FirstName of the telegram profile')),
                ('hash', models.CharField(verbose_name='Hash of the telegram profile')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='telegram id profile')),
                ('photo_url', models.CharField(verbose_name='Photo_Url of the telegram profile')),
                ('username', models.CharField(verbose_name='UserName of the telegram profile')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(default='etc', max_length=10, verbose_name='Key of key category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Name of the category'),
        ),
    ]
