# Generated by Django 4.2.5 on 2023-11-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0009_profile_alter_category_key_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(default='etc', max_length=10, unique=True, verbose_name='Key of key category'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='siteApp.item', verbose_name='items of cart')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteApp.cart'),
        ),
    ]
