# Generated by Django 4.2.5 on 2023-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0012_cart_remove_profile_cart_cartitem_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, to='siteApp.item', verbose_name='arr of the cart items'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
